name: user_repository
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  rxdart: 0.27.7
  flutter_secure_storage: 7.0.1

dev_dependencies:
  mockito: 5.3.2
  test: ^1.16.8
  lints: 2.0.1
  build_runner: ^2.3.3