name: quote_details
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  share_plus: ^6.3.0
  flutter:
    sdk: flutter
  quote_repository:
    path: ../../quote_repository
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  test: ^1.16.8
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true