name: sign_in
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mockito: 5.3.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true