name: monitoring
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_dynamic_links: ^5.0.11
  firebase_analytics: ^10.1.0
  firebase_remote_config: ^3.0.9

dev_dependencies:
  lints: 2.0.1
  test: ^1.16.8