name: fav_qs_api
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.8.0

dev_dependencies:
  http_mock_adapter: ^0.3.3
  mockito: 5.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.16.8
  lints: 2.0.1